replicaCount: 3

image:
  repository: 183678667273.dkr.ecr.us-east-1.amazonaws.com/three-tier-frontend
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: opsfusion.in
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

rollout:
  autoPromotionEnabled: false
  scaleDownDelaySeconds: 60
