replicaCount: 2

image:
  repository: 183678667273.dkr.ecr.us-east-1.amazonaws.com/three-tier-frontend
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: uat.opsfusion.in
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi

rollout:
  autoPromotionEnabled: false
  scaleDownDelaySeconds: 30

database:
  host: postgres-rds-sg.c4dqoyue0lsc.us-east-1.rds.amazonaws.com
  readHost: postgres-rds-sg-read-1.c4dqoyue0lsc.us-east-1.rds.amazonaws.com
  port: "5432"
  name: postgres
  user: mypostgresqlu1
  password: "mypostgresqlu1123"
