apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: production
type: Opaque
stringData:
  DB_HOST: postgres-rds-sg.c4dqoyue0lsc.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: mypostgresqlu1
  DB_PASSWORD: "mypostgresqlu1123"
