apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "three-tier-pgsql.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ dig "database" "host" "" .Values | quote }}
  DB_READ_HOST: {{ dig "database" "readHost" (dig "database" "host" "" .Values) .Values | quote }}
  DB_PORT: {{ dig "database" "port" "5432" .Values | quote }}
  DB_NAME: {{ dig "database" "name" "" .Values | quote }}
  DB_USER: {{ dig "database" "user" "" .Values | quote }}
  DB_PASSWORD: {{ dig "database" "password" "" .Values | quote }}
